### ISSUE TITLE
Add LJH 2.0.0 handling

### ISSUE THREAD

**Issue by joefowler** [usnistgov/Pope.jl#10]
I have some 2011 data that I used for the multi-pulse fitting paper and which I'll use for the new analysis on records of unequal size (ROUSs). They are in LHJ 2.0.0 format. For now, I am analyzing them outside of the Pope framework, and there's a 2.0.0 reader. But I think it is not insane to imagine a unification of ROUS analysis with Pope, and then we will want to be able to test it out on the 2011 data.

No hurry, but for this purpose, I'll need to add LJH 2.0.0 handling into Pope.

**Comment by ggggggggg** [comment]
2.0? Even more ancient than 2.1? I thought even 2.1 was so ancient it would not be used. But clearly I'll be proven wrong. Shouldn't be hard to add.

**Comment by joefowler** [comment]
Well, I feel a little silly adding support for data so ancient, but the fact is that I have returned to our very cleanest 2011 data over and over, and there's no sign that it will ever stop! So it seems better to add this capability wherever other LJH handling happens, because the alternative is to require special handling for some data versus other data.

**Comment by ggggggggg** [comment]
nice! I took a quick look at the code and it looks like you did a good job of re-using code across LJH versions.
