### ISSUE TITLE
Make Pope compatible with Julia 0.7

### ISSUE THREAD

**Issue by joefowler** [usnistgov/Pope.jl#17]
We are going to need to make Pope work on Julia version 1. Start by getting to 0.7, of course.

**Comment by joefowler** [comment]
@ggggggggg, I know that you aren't interested in getting to Julia 1.0 yet, but I thought I would explore the question of whether scripts start any faster in 0.7. The answer seems to be no, though perhaps there are precompile options that I didn't learn about yet.

I tried running `noise_analysis.jl` on an 8-channel directory and then `noise_plots.jl` on the HDF5 file it produced. The former averaged 115 seconds in Julia 0.6.4 vs 127 seconds in version 0.7. Similarly, the plots required 77-88 seconds in 0.6.4 and 90-95 seconds in 0.7.0. I suppose I could have minimized the effect of computation time by limiting the analysis to `--maxchannels 1`, but I did not do that.

I changed only enough in the branch `julia0.7` to make those two scripts run and removed most (but not all) deprecation warnings. I continue to have zero understanding whatsoever of the new package manager, so I cannot even get the answer to whether Pope can pass tests locally. (I mean, it can't pass, but the error is about dependencies, not about Pope's code-correctness.)

**Comment by joefowler** [comment]
Discussed today. Decided that we can move to Julia 1 without several of the source files that we don't use any more.

**Comment by ggggggggg** [comment]
We don't have to transition immediatly, but it would make tests faster if we just start deleting unused code as we go through, we can always dig it back out with git. The easiest would really be to just delete the test associated with unused code, and I think the slowest tests are in a testset called "scripts".

**Comment by joefowler** [comment]
Fixed by #23
