### ISSUE TITLE
Unify LJH File handling

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/Pope.jl#5]
Joe wants to allow the use of globs, eg "a/b/c_chan*.ljh" for arguments into scripts. Galen is basically on board, but has previously used "a/b/c_chan1.ljh" with additional code to sort out which channels exist and which to use.

Should we support multiple ljh file groups in the same directory?
a/b/c_chan1.ljh
a/b/d_chan1.ljh

Assuming the following files exist
a/b/c_chan1.ljh
a/b/c_chan2.ljh

API goals:
`./myscript a/b/c_chan*.ljh` opens both files
`./myscript a/b` opens both files
`./myscript a/b/c_chan1.ljh` fails
`./myscript a/b channels=1` opens only channel 1
`./myscript a/b maxchannels=1` opens only channel 1

**Comment by ggggggggg** [comment]
How do you specify both noise and pulse files, as you would want to for `make_preknowledge` and might want to with a `build_basis` script that does noise analysis and pulse analysis?
Assume:
pulse files: a/a_chan1.ljh, a/a_chan2.ljh, etc
noise files: b/b_chan1.ljh, b/b_chan2.ljh, etc
`./myscript

**Comment by joefowler** [comment]
In the case where you want to introduce both noise and pulse data into the same analysis, I'd argue that you generally don't want noise LJH files as an input. They should be analyzed first, and separately via `noise_analysis.jl`. Then their `NoiseResult` object can be loaded from HDF5 files for any later pulse-based analysis.

**Comment by ggggggggg** [comment]
So the command line API will be
```
./noise_analysis noisefile --options
./basis_generate noiseoutput pulsefile --options
./popeonce basisoutput newpulsefile --options
```
???

**Comment by ggggggggg** [comment]
Since globbing in bash just means argparse returns a list, I think we can use multiple dispatch on `LJH.allchannels` to support this.

**Comment by joefowler** [comment]
I like the command-line workflow that you outlined. I think it's great in one particular way: you can use one noise file in generating multiple basis files, and you can use each basis file with multiple pulse files. The workflow you give emphasizes precisely this fact. So perhaps a better way to think about it would be this:

```bash
./noise_analysis noisefiles --options

# Generate a basis using pulse-training data A
./basis_generate noiseoutput pulsefilesA --options
./popeonce basisoutputA newpulsefiles1 --options
./popeonce basisoutputA newpulsefiles2 --options

# Now for some reason, the noise is still valid, but we need a new basis from training data B.
./basis_generate noiseoutput pulsefilesB --options
./popeonce basisoutputB newpulsefiles3 --options
./popeonce basisoutputB newpulsefiles4 --options
```

The same noise is used to generate 2 basis files, which are then used to analyze 4 separate sets of spectroscopy data.

**Comment by ggggggggg** [comment]
Assuming the following files exist
a/b/c_chan1.ljh
a/b/c_chan2.ljh


API goals:
These three calls are equivalent and open both files:
  * `./myscript a/b/c_chan*.ljh` 
  * `./myscript a/b` 
  * `./myscript a/b/c_chan1.ljh` 
Use `channels` OR `maxchannels` optional arguments to get fewer channels
  * `./myscript a/b channels=1,2` opens both
  * `./myscript a/b channels=1` opens only channel 1
  * `./myscript a/b maxchannels=1` opens only channel 1

**Comment by joefowler** [comment]
I have been developing the `noise_analysis.jl` with the expectation that users would pass `/a/b/c_chan*.ljh` as its globbable (?) argument. I don't see why it's so hard. We could later add the option of passing `/a/b/` and running on all LJH files in that directory.

If you really want to use the API goals that you listed on Dec 22, then let's discuss. They won't be hard to do.

To help with these and other goals, I can make sure that the script silently ignores inputs like `/a/b/c.ljh`, which is easy to recognize when the attempt to decode the channel number fails.

**Comment by joefowler** [comment]
It's been 18 months. I think this issue is resolved in some fashion. Let's close it.
